apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front-end-demo1
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/georgegoglodze/argocd.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: demo-ns

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
