apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  selector:
    matchLabels:
      app: payment
  replicas: 2
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
