apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment1-deployment
spec:
  selector:
    matchLabels:
      app: payment1
  replicas: 2
  template:
    metadata:
      labels:
        app: payment1
    spec:
      containers:
      - name: payment1
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
